### ISSUE TITLE
Error when installing docker due to dependency naming

### ISSUE THREAD

**Issue by rdinizcal** [Gastd/eclipse-2022-03-docker#1]
![image](https://user-images.githubusercontent.com/18559295/175495032-3f39f3ad-7c6d-4dd3-aa36-0535946b27ad.png)

Worked after renaming the .deb file:
```mv jdk-18.0.1.1_linux-x64_bin.deb jdk-18_linux-x64_bin.deb```

**Comment by Gastd** [comment]
Readme updated. Thanks!
